name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    
    - name: setup go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build
      run: go build -o go-web-app

    - name: test
      run: go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with: 
        version: v1.56.2
    
  push:
    runs-on: ubuntu-latest

    needs: build
    steps:
    - name: checkoutcode
      uses: actions/checkout@v4

    - name: setup docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: login to DockerHub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}
  
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: update tag in helm chart 
      run: |
        sed -i 's/tag: .*/tag: "${{github_run_id}}"/' helm/go-web-app-chart/values.yaml
    
    - name: commit and push changes
      run: |
        git config --global user.email "admin@hmail.com"
        git config --global user.name "admin"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "updated image tag"
        git push
